### ISSUE TITLE
error with command npx gltfjsx

### ISSUE THREAD

**Issue by ppacory** [pmndrs/gltfjsx#149]
After command : npx gltfjsx model.glb 

```
TypeError: Failed to parse URL from /Documents/GIT/threejs/2022/sandbox.15.06.22/node_modules/draco3dgltf/draco_decoder_gltf.wasm
    at new Request (node:internal/deps/undici/undici:4813:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:5539:29)
    at Object.fetch (node:internal/deps/undici/undici:6370:20)
    at fetch (node:internal/bootstrap/pre_execution:196:25)
    at /Documents/GIT/threejs/2022/sandbox.15.06.22/node_modules/draco3dgltf/draco_decoder_gltf_nodejs.js:39:485
    at /Documents/GIT/threejs/2022/sandbox.15.06.22/node_modules/draco3dgltf/draco_decoder_gltf_nodejs.js:40:128
    at Object.createDecoderModule (/Documents/GIT/threejs/2022/sandbox.15.06.22/node_modules/draco3dgltf/draco_decoder_gltf_nodejs.js:40:151)
    at Object.<anonymous> (/Documents/GIT/threejs/2022/sandbox.15.06.22/node_modules/gltfjsx/src/bin/DRACOLoader.js:2:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

my npm list :  
├── @emotion/react@11.9.0
├── @emotion/styled@11.8.1
├── @fontsource/inter@4.5.11
├── @mui/icons-material@5.8.2
├── @mui/material@5.8.2
├── @mui/system@5.8.2
├── @react-three/drei@9.13.0
├── @react-three/fiber@8.0.22
├── @testing-library/jest-dom@5.16.4
├── @testing-library/react@13.3.0
├── @testing-library/user-event@13.5.0
├── @use-gesture/react@10.2.15
├── draco3d@1.5.2
├── gltfjsx@4.6.4
├── meshline@2.0.4
├── randomcolor@0.6.2
├── react-color@2.19.3
├── react-dom@18.1.0
├── react-scripts@5.0.1
├── react@18.1.0
├── three@0.141.0
├── web-vitals@2.1.4
└── zustand@4.0.0-rc.1

**Comment by soul-on-you** [comment]
I have the same problem

**Comment by ppacory** [comment]
i use this to transform to mesh : https://gltf.pmnd.rs/

**Comment by benjaminha14** [comment]
same, having the same problem

**Comment by willmadd** [comment]
Seems that the package is not compatible with node 18, I downgraded to node 16 and it works fine.

**Comment by superdwayne** [comment]
Saved my sanity thank you @willmadd

**Comment by drcmda** [comment]
i think nothing at the moment is compatible with node 18, i can't run anything, bundlers, all out of order due to breaking changes in some low level ssl stuff.

**Comment by LvLs9** [comment]
Thanks! I think, it'll be cool to add notes about Node 16 to README
