### ISSUE TITLE
cannot run my model

### ISSUE THREAD

**Issue by xiaogua-bushigua** [pmndrs/gltfjsx#205]
when I run "npm exec gltfjsx@6.2.0 .\rabbitDraco.gltf -T"

an error occurs：

file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/options.js:15
                                filter: ([, flag]) => Object.hasOwn(flag, 'alias'),
                                                             ^

TypeError: Object.hasOwn is not a function
    at filter (file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/options.js:15:34)
    at file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/options.js:42:58
    at Array.filter (<anonymous>)
    at validateOptions (file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/options.js:42:41)
    at buildOptions (file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/options.js:87:2)
    at meow (file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/meow/source/index.js:91:24)
    at file:///C:/Users/1/AppData/Local/npm-cache/_npx/d2e3f27ebeaf007c/node_modules/gltfjsx/cli.js:13:13
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)

**Comment by drcmda** [comment]
it should be npx gltfjsx yourmodel.glb --transform

the model also needs to access its externals, if that's an empty gltf and the binaries aren't there it cant work
