### ISSUE TITLE
Failure when not transforming gltf file

### ISSUE THREAD

**Issue by benthillerkus** [pmndrs/gltfjsx#276]
File here: [venice.zip](https://github.com/user-attachments/files/17029941/venice.zip)
`npx gltfjsx@6.5.0 public\\assets\\venice.glb --root=.\\public --output=public\\assets\\model.tsx`

When not transforming the file, gltfjsx crashes with the following trace:

```
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public\\assets\\venice.glb --root=.\\public --output=public\\assets\\model.tsx --typed
*/
SyntaxError: Expected corresponding JSX closing tag for <instancedMesh>. (232:1)
  230 | <instancedMesh args={[nodes.Balcony001.geometry, nodes.Balcony001.material, 7]} instanceMatrix={nodes.Balcony001.instanceMatrix} position={[2.281, 4.184, 2.723,]} rotation={[0, -Math.PI / 2, 0,]} >
  231 | <mesh geometry={nodes.Balcony.geometry} material={nodes.Balcony.material} rotation={[0, 1.571, 0,]} />
> 232 | </mesh><instancedMesh args={[nodes.Balcony002.geometry, nodes.Balcony002.material, 7]} instanceMatrix={nodes.Balcony002.instanceMatrix} position={[2.281, 4.184, 4.754,]} rotation={[0, -Math.PI / 2, 0,]} >
      | ^
  233 | <mesh geometry={nodes.Balcony_1.geometry} material={nodes.Balcony_1.material} rotation={[0, 1.571, 0,]} />
  234 | </mesh>
  235 |             </group>
    at Ur (D:\projects\venezia-website\node_modules\gltfjsx\node_modules\prettier\plugins\babel.js:15:1323)
    at jr (D:\projects\venezia-website\node_modules\gltfjsx\node_modules\prettier\plugins\babel.js:15:1545)
    at Object.parse (D:\projects\venezia-website\node_modules\gltfjsx\node_modules\prettier\plugins\babel.js:16:16950)
    at parse (file:///D:/projects/venezia-website/node_modules/gltfjsx/node_modules/prettier/index.mjs:19362:24)
    at async coreFormat (file:///D:/projects/venezia-website/node_modules/gltfjsx/node_modules/prettier/index.mjs:20683:7)
    at async formatWithCursor (file:///D:/projects/venezia-website/node_modules/gltfjsx/node_modules/prettier/index.mjs:20885:14)
    at async Module.format2 (file:///D:/projects/venezia-website/node_modules/gltfjsx/node_modules/prettier/index.mjs:24517:25)
    at async file:///D:/projects/venezia-website/node_modules/gltfjsx/src/gltfjsx.js:69:26
```

**Comment by benthillerkus** [comment]
This was fixed in https://github.com/pmndrs/gltfjsx/commit/fe18a6e82a7309520fb39a0a8a0b7cb581d96f40
