### ISSUE TITLE
Invalid typed array length: 1980

### ISSUE THREAD

**Issue by hjopel** [pmndrs/gltfjsx#75]
Hi all. Thanks for this library. 

Previously, I've been using quite some Three.js and now want to combine it with react. Everything works fine. When I want to convert for example the Buggy.gltf from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF, it works perfectly and I get the .js file. Once I placed this file in my src/components/Models and use it in my program, I get this error: 

Uncaught Invalid typed array length: 1980
index.js:1 The above error occurred in the <Model> component:

    at Model (http://localhost:3000/static/js/main.chunk.js:422:69)
    at Suspense
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:11709:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
react-reconciler.development.js:2559 Uncaught Invalid typed array length: 1980
index.js:1 The above error occurred in the <Canvas> component:

    at Canvas (http://localhost:3000/static/js/vendors~main.chunk.js:11481:3)
    at Loading (http://localhost:3000/static/js/main.chunk.js:291:1)
    at header
    at div
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
react-dom.development.js:11340 Uncaught Invalid typed array length: 1980

In the following I will include the code and the layout of my app:
![image](https://user-images.githubusercontent.com/70332133/114201013-11373500-9956-11eb-923d-c4d71383913a.png)

![image](https://user-images.githubusercontent.com/70332133/114201078-20b67e00-9956-11eb-8397-2081ae4e41f1.png)

![image](https://user-images.githubusercontent.com/70332133/114201132-2ad87c80-9956-11eb-98e3-dbc82fbf3ac0.png)

![image](https://user-images.githubusercontent.com/70332133/114201158-32982100-9956-11eb-9733-d54a46dd6177.png)

**Comment by hjopel** [comment]
my bad, forgot to add the .bin file to public
